version: 2
jobs:
  build:
    docker:
      - image: greysonr/lobby_server:0.0.1

    steps:
      - checkout

      - run:
          name: install
          command: yarn install

      - run:
          name: start
          command: yarn start
          background: true

      - run:
          name: wait_for_server
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000/
            :

      - run:
          name: test
          command: yarn test

  deploy:
    docker:
      - image: greysonr/lobby_server:0.0.1

    steps:
      - checkout

      - run:
          name: install
          command: yarn install

      - add_ssh_keys:
          fingerprints:
            - "e9:82:1d:cc:68:5a:16:5e:ac:53:72:e5:17:03:b5:ca"

      - run:
          name: insert public key
          command: echo "$deploy_public_key" > ~/.ssh/lobby_server_deploy2_rsa.pem

      - run:
          name: add server to known_hosts
          command: echo "$SERVER_KNOWN_HOSTS_ENTRY" >> ~/.ssh/known_hosts

      - run:
          name: deploy
          command: yarn pm2 deploy ecosystem.config.js production

workflows:
  version: 2
  Build_and_Deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
